In [28]:
import pandas as pd
import numpy as np
import pathlib

imdb_data_dir = pathlib.Path('../../code/letterbox-data').resolve()

# ratings
ratings = pd.read_csv(
        pathlib.Path(imdb_data_dir / 'ratings.csv'),
        delimiter=',',
        low_memory=False
)

# change name to lower, and remove spaces
ratings['Name'] = ratings['Name'].str.lower() 
ratings['Name'] = ratings['Name'].str.strip().replace(r'\s+', '', regex=True)
ratings['Name'] = ratings['Name'].astype('string')

In [27]:
### from other sheet #####
import pandas as pd
import numpy as np
import pathlib
titles = pd.read_csv(
        pathlib.Path('./data/title.basics.tsv').resolve(),
        delimiter='\t',
        index_col=['tconst'],
        na_values=['\\N'],
        low_memory=False
)
imdb_ratings = pd.read_csv(
        pathlib.Path('./data/title.ratings.tsv').resolve(),
        delimiter='\t',
        index_col=['tconst'],
        na_values=['\\N'],
        low_memory=False
)

# Combine data-sources on 'tconst' (works like left inner join)
df = pd.merge(titles, imdb_ratings, on="tconst")

# Clean up runtimeMinutes data
df['runtimeMinutes'] = df['runtimeMinutes'].fillna(0)
df = df[df['runtimeMinutes'].str.isnumeric().astype('bool')].copy()
df['runtimeMinutes'] = pd.to_numeric(df['runtimeMinutes'])
################################

In [29]:
df['Name'] = df['originalTitle'].str.lower() 
df['Name'] = df['Name'].str.strip().replace(r'\s+', '', regex=True)
df['Name'] = df['Name'].astype(str)

Date               object
Name               object
Year              float64
Letterboxd URI     object
Rating            float64
dtype: object

In [74]:
#movies = df.iloc[np.where(df.titleType == 'movie')].copy()

# pd.merge(movies, ratings, left_on=['Name', 'startYear'], right_on=['Name', 'Year'], how='right')

movies

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,Name
tconst,,,,,,,,,,,
tt0000009,movie,Miss Jerry,Miss Jerry,0.0,1894.0,NaN,45,Romance,5.3,220,missjerry
tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,0.0,1897.0,NaN,100,"Documentary,News,Sport",5.3,549,thecorbett-fitzsimmonsfight
tt0000502,movie,Bohemios,Bohemios,0.0,1905.0,NaN,100,NaN,3.8,20,bohemios
tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0.0,1906.0,NaN,70,"Action,Adventure,Biography",6.0,971,thestoryofthekellygang
tt0000591,movie,The Prodigal Son,L'enfant prodigue,0.0,1907.0,NaN,90,Drama,5.6,30,l'enfantprodigue
...,...,...,...,...,...,...,...,...,...,...,...
tt9916362,movie,Coven,Akelarre,0.0,2020.0,NaN,92,"Drama,History",6.4,6002,akelarre
tt9916428,movie,The Secret of China,Hong xing zhao yao Zhong guo,0.0,2019.0,NaN,0,"Adventure,History,War",4.5,22,hongxingzhaoyaozhongguo
tt9916538,movie,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,0.0,2019.0,NaN,123,Drama,8.3,9,kuambillagihatiku
tt9916706,movie,Dankyavar Danka,Dankyavar Danka,0.0,2013.0,NaN,0,Comedy,7.7,9,dankyavardanka
tt9916730,movie,6 Gunn,6 Gunn,0.0,2017.0,NaN,116,Drama,7.0,12,6gunn